### ISSUE TITLE
How to share typescript types between frontend and backend

### ISSUE THREAD

**Issue by bebu259** [anomalyco/sst#2138]
I have a SST project with an AppSync GraphQL backend and a React frontend.

Is there a way to share typescript types between frontend and backend?

I tried typescript's [path mapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) but unfortunately had no luck with it. Neither when the types are defined in the frontend nor in the backend.

In `tsconfig.json` in the backend I added this:
```json
"compilerOptions": {
  "baseUrl": ".",
  "paths": {
    "@frontend": ["../frontend/src/types"]
  }
}
```
and tried to import types like this:
```js
import { Product } from "@frontend/models/product";
```

**Comment by SpencerDuball** [comment]
A common pattern to get typings defined once and shared in the Frontend/Backend/Any other is with a monorepo and a package manager such as pnpm or yarn. I am personally partial to pnpm and this is a great article where they talk explicitly about sharing types between frontend and backend: 
https://blog.logrocket.com/managing-full-stack-monorepo-pnpm/#sharing-types-typescript

Basically you define a shared package such as "shared" and then you can import this into both the frontend and backend.

**Comment by lefnire** [comment]
Use npm "modules", see this gist for example https://gist.github.com/lefnire/6da993dcdf8280c5d22e6359a986ecfd . LMK if you need help and I'll add more details to the gist

**Comment by andykenward** [comment]
@bebu259 I changed the tsconfig alias to using pnpm workspaces. This then allows you to use internal npm packages. If you see how [Turborepo - internal packages](https://turbo.build/repo/docs/handbook/sharing-code/internal-packages) does this. You don't have to use Turborepo for this, but you do need to use pnpm workspaces.

For example
`frontend/packages.json`
```json
{
  "name": "@frontend",
  "version": "0.0.0",
  "type": "module",
  "main": "src/index.ts",
  "types": "src/index.ts",
  "dependencies": {
    "@backend": "workspaces:*",
    "typescript": "latest"
  }
}
```

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
