### ISSUE TITLE
Type error in Cognito authorization examples

### ISSUE THREAD

**Issue by jbhammon** [anomalyco/sst#2356]
Hi all,

I was working through the guide setting up my first project using Typescript and I'm struggling through some type errors with `aws-lambda`. Specifically, I had this problem on [this step of the guide.](https://sst.dev/chapters/secure-our-serverless-apis.html)

It seems like `event.requestContext` has no `authorizer` attribute. Typescript error is: 

```
Property 'authorizer' does not exist on type 'APIGatewayEventRequestContextV2'.ts(2339)
```

I wasn't sure if I had my dependencies installed wrong so I also checked one of the example starter projects that `create-sst` can make, specifically `examples/api-auth-cognito`. Commands to do that were:

```bash
npx create-sst@latest dummy-project-name

? What kind of project do you want to create? examples
? Select a template examples/api-auth-cognito
```

After running `npm install` in that new project I opened the `services/functions/private.ts` file, which tries to access the same `authorizer` attribute, and saw the same type error.

Is there a different way we should be trying to access the Cognito info from these API Gateway events, or maybe `aws-lambda` changed their types since these examples were created?

**Comment by busla** [comment]
would be great to get some input from the maintainers

**Comment by jayair** [comment]
So I've run into this before and I think the type support for those handlers isn't great. I'll need to spend some time to figure out if there's a better way to do this without creating a custom handler.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
