### ISSUE TITLE
[feature-request] native support for OpenAPI/SpecRestApi

### ISSUE THREAD

**Issue by drissamri** [anomalyco/sst#2861]
In most of my enterprise clients, they love to use contract-first development with Swagger/OpenAPI. 

AWS/CDK has good support for this through the [SpecRestApi](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway.SpecRestApi.html) that configures your API Gateway based on the API contract, so the contract and implementation are always in sync. 

Are they any plans to support this in SST? Or what's the prefered way of doing this in SST right now? 

I guess this is more a enterprise feature then what most people use to bootstrap their projects, but it would open up a lot of new big companies to SST I think. This is the only reason currently holding me back for SST on client projects. 

An example in CDK: 

    private createRestApi(props: ApiStackConfigProps, createArn: string, getArn: string): SpecRestApi {
        const apigwLogGroup = new LogGroup(this, 'ApiGWLogs', {
            retention: RetentionDays.ONE_WEEK,
        });

        let api = new SpecRestApi(this, 'ChaosApi', {
            restApiName: `ChaosApi${props.suffix}`,
            apiDefinition: ApiDefinition.fromInline(
                this.generateOpenApiSpec({
                    CreateArtistLambda: createArn,
                })),
            deployOptions: {
                loggingLevel: MethodLoggingLevel.ERROR,
                accessLogDestination: new LogGroupLogDestination(apigwLogGroup),
                accessLogFormat: AccessLogFormat.jsonWithStandardFields(),
                metricsEnabled: true,
                tracingEnabled: true,
            },
            endpointTypes: [EndpointType.REGIONAL],
        });

        return api;
    }

**openapi.yaml**

    openapi: 3.0.3
    info:
      version: 1.0.0
      title: Simple Artist API
      description: A simple API to illustrate OpenAPI concepts
    
    paths:
      /artists:
        post:
          description: Lets a user post a new artist
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Artist'
    
          responses:
            '200':
              description: Successfully created a new artist
            '400':
              $ref: '#/components/responses/400Error'
          x-amazon-apigateway-integration:
            uri: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/{{CreateArtistLambda}}/invocations"
            passthroughBehavior: "when_no_match"
            httpMethod: "POST"
            type : "aws_proxy"

**Comment by jayair** [comment]
Does the CDK construct work in SST? Or are you looking for a nicer way to do it?

**Comment by earlyster** [comment]
I would look at what this project is doing to create constructs for OpenAPI https://github.com/alma-cdk/openapix/ -- I had trouble using it due to Auth.auth requires SST.API and you cannot pass in apigateway.RestApi or apigateway.SpecRestApi

**Comment by elkouhen** [comment]
Hello 
The same with the ion engine would be great
Thanks

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
