### ISSUE TITLE
Extremely high CPU usage during Live Lambda Development

### ISSUE THREAD

**Issue by 525c1e21-bd67-4735-ac99-b4b0e5262290** [anomalyco/sst#3437]
When making any more than a trivial number of requests to a lambda via Live Lambda Development, the host process uses an excessive amount of CPU.

In addition, the large amount of CPU usage causes the lambdas to take several minutes to complete which additionally causes the proxy to hang up with 503s.

This does not occur when the lambdas are harnessed via some vanilla node code or when deployed concretely to AWS.

Software:
- sst@2.31.0
- aws-cdk-lib@2.101.1
- node@18.18.2
- MacOS 14.0

Hardware: Apple M2 Max (32 GB)

**Comment by jayair** [comment]
That's really weird. Let's debug this, can you open a thread in #help in Discord?
