### ISSUE TITLE
How can I define s3 lifecycle deletion policy?

### ISSUE THREAD

**Issue by agamm** [anomalyco/sst#3926]
I want to delete files after a few hours, is it possible somehow with `Bucket`?

**Comment by agamm** [comment]
Eventually I figured it out
```

const bucket = new sst.aws.Bucket("MyBucket");

// Delete files after 1 day
const lifecycleRule = new aws.s3.BucketLifecycleConfigurationV2(
	"lifecycleRule",
	{
		bucket: bucket.name,
		rules: [
			{
				id: "delete-after-1-day",
				status: "Enabled",
				expiration: {
					days: 1, // 24 hours
				},
			},
		],
	},
);
```

**Comment by Prinzhorn** [comment]
@agamm thanks a lot! Maybe you can open your PR to the new repo (seems like the issue was transferred but not your PR). Would be highly appreciated to have more real world examples.

Pulumi docs also say:

> Deprecated: aws.s3/bucketlifecycleconfigurationv2.BucketLifecycleConfigurationV2 has been deprecated in favor of aws.s3/bucketlifecycleconfiguration.BucketLifecycleConfiguration

**Comment by agamm** [comment]
> [@agamm](https://github.com/agamm) thanks a lot! Maybe you can open your PR to the new repo (seems like the issue was transferred but not your PR). Would be highly appreciated to have more real world examples.
> 
> Pulumi docs also say:
> 
> > Deprecated: aws.s3/bucketlifecycleconfigurationv2.BucketLifecycleConfigurationV2 has been deprecated in favor of aws.s3/bucketlifecycleconfiguration.BucketLifecycleConfiguration

Sorry I am not using sst right now so it's a bit out of focus to put more time into this.
