### ISSUE TITLE
[ION-1287] Docs: review VPC NAT

### ISSUE THREAD

**Issue by fwang** [anomalyco/sst#4068]
NAT used to take `"ec2" | "managed"`, now we also allow ppl to customize the ec2 instance type:

```ts
new sst.aws.Vpc("Vpc", {
  nat: {
    ec2: { instance: "t4g.micro" }
  }
});
```

See if the doc is clear - [https://sst.dev/docs/component/aws/vpc#nat](https://sst.dev/docs/component/aws/vpc#nat)

<sub>[ION-1287](https://linear.app/sst-dev/issue/ION-1287/docs-review-vpc-nat)</sub>

**Comment by cyril94440** [comment]
Hi there

I have tested ec2 : "nat" or specifying an instance type, but it hangs forever

`Creating    MyVPC sst:aws:Vpc → MyVPCNatInstance2 aws:ec2:Instance`


Any idea?

thanks

**Comment by jayair** [comment]
It does take some time to create these. If it's taking longer than 10mins or so, open a new issue?
