### ISSUE TITLE
.env.{stage} not being picked up during sst dev

### ISSUE THREAD

**Issue by kmcaloon** [anomalyco/sst#4329]
I have a NextJS app that needs to use some sst resources. When running `sst dev -- next dev` everything looks good, except it looks like `sst.config.ts` is only picking up environment variables from `.env`. Any other files like `.env.local` never get loaded. When I remove `.env`, sst then throws an error because the variables are missing.

From what I understand, is it not supposed to automatically work with .env.{stage} files?

**Comment by JINGBANZ** [comment]
i am facing the same issue. i ran `yarn sst deploy --stage production`, but it is not picking up the .env.production file

**Comment by brandonin** [comment]
I have also tried this, although it shows that it was picking up my .env.production.local, it did not actually inject it. This generally wouldn't be an issue other than the fact that I am using Clerk which doesn't really allow me to inject the secret keys.

EDIT: Strangely when I change .env.production.local to .env.production it starts picking it up...
