### ISSUE TITLE
Server responses in sst.aws.Function are wrapped inside another Response

### ISSUE THREAD

**Issue by roguesherlock** [anomalyco/sst#4520]
Basically if you run any server inside an aws function like say hono, it seems to wrap the response of the server inside a another response with its body being the response of the server.

For example here's the response I get in dev mode,
```
{
    "body": "{\"isBase64Encoded\":false,\"awsRequestId\":\"298b1fd2-2a50-48ae-b624-ab9ac1693a21\"}",
    "headers": {
        "content-type": "application/json; charset=UTF-8"
    },
    "statusCode": 200,
    "isBase64Encoded": false
}
```

And here's the expected response for an api response,
```
{"isBase64Encoded":false,"awsRequestId":"7d3c788f-adde-4f58-995e-98a250fb20c4"}
```

~~Note that it works correctly in prod.~~

Edit:
I didn't test this properly. It looks like it doesn't work in prod either

**Comment by KurtGokhan** [comment]
I had `streaming: true` and changing it to `streaming: !$dev` works. But it doesn't happen automatically as @thdxr said.
