### ISSUE TITLE
Add a command to the CLI to generate types

### ISSUE THREAD

**Issue by bchilcott** [anomalyco/sst#4581]
There should be a command to generate types without having to deploy the whole app, for type checking/linting in CI, etc.

**Comment by srenault** [comment]
Any news on this? Right now we have to run `sst dev` in the CI to generate the types and run `tsc`. I don't like the idea of commiting the types along with the code source. It's very easy for someone to push outdated types and deploy a broken version. What do you think @thdxr ?
