### ISSUE TITLE
Missing Polyfills with Cloudflare compat v2

### ISSUE THREAD

**Issue by claughinghouse** [anomalyco/sst#4953]
When deploying better-auth with CF workers SST errors out with the following:

```
✕  Failed
   Api sst:cloudflare:Worker → ApiScript cloudflare:index:WorkerScript
     sdk-v2/provider2.go:520: sdk.helper_schema: error updating worker script: Uncaught SyntaxError: The requested module 'node:process' does not provide an export named 'stdin'
  at worker.mjs:824:9
 (10021): provider=cloudflare@5.41.0

   Api sst:cloudflare:Worker → ApiScript cloudflare:index:WorkerScript
   SyntaxError: The requested module 'node:process' does not provide an export named 'stdin'
   at worker.mjs:824:9
   (10021)
```

sst version: 3.2.47
better-auth: 0.5.2-beta.13 (latest avaliable). 

ref: https://discord.com/channels/983865673656705025/1297272657808461927

**Comment by claughinghouse** [comment]
Fixed via https://discord.com/channels/983865673656705025/1297272657808461927

**Comment by claughinghouse** [comment]
Fixed via https://discord.com/channels/983865673656705025/1297272657808461927

**Comment by tspader** [comment]
Why are we linking to Discord in GH issues? Where did we go wrong as a society?
