### ISSUE TITLE
Add static get method to Secret component

### ISSUE THREAD

**Issue by joshymcd** [anomalyco/sst#4956]
there are some secrets that i would like to share across my development stages, for example i use clerk for authentication and they give you one live and one test/dev instance i would like to share across all non prod stages

**Comment by jayair** [comment]
Have you tried using the `--fallback` flag? https://sst.dev/docs/reference/cli#secret

**Comment by joshymcd** [comment]
Ahh, missed this in the docs :) ill give it a try
