### ISSUE TITLE
Error: Runtime not found: `provided.al2023`

### ISSUE THREAD

**Issue by imjulianeral** [anomalyco/sst#4960]
Hello there!

I'm using the runtime `provided.al2023`  in my lambdas but after upgrading SST to the latest version and performing a deploy it throws an error:

- Error: Runtime not found: `provided.al2023`

In the version: 3.1.29 works perfectly fine.

**Comment by thdxr** [comment]
potentially fixed in v3.2.49

**Comment by imjulianeral** [comment]
I confirm that it's already solved.
