### ISSUE TITLE
Bug: npm exec -- sst tunnel → panic: runtime error: slice bounds out of range [:255] with length 40

### ISSUE THREAD

**Issue by joegearlesss** [anomalyco/sst#4971]
- Got error on `npm exec -- sst tunnel` with `sst@3.2.52`
- use vscode on mac

```
panic: runtime error: slice bounds out of range [:255] with length 40
```

**Comment by IWhitebird** [comment]
same

**Comment by IWhitebird** [comment]
getting the same error using bun and linux

**Comment by a-eid** [comment]
for me 

```bash 
$ sst dev 
```

return this error 

```bas
panic: runtime error: slice bounds out of range [:255] with length 194

goroutine 1 [running]:
main.main()
        /home/runner/work/sst/sst/cmd/sst/main.go:62 +0x7b0
```

**Comment by a-eid** [comment]
make sure you have your `CLOUDFLARE_API_TOKEN` in your `.env` file.

**Comment by thdxr** [comment]
fixed in v3.2.53

**Comment by dpeek** [comment]
Seems to still be an issue:

<img width="534" alt="image" src="https://github.com/user-attachments/assets/35e43a4b-ff77-4580-9b74-05a4c2e37f17">

**Comment by jayair** [comment]
@dpeek is this for all commands?

Can you try the latest btw?
