### ISSUE TITLE
Bug: global install script fails for version 3.2.41 onwards after the repo move

### ISSUE THREAD

**Issue by aatecey** [anomalyco/sst#4975]
```
curl -fsSL https://sst.dev/install | VERSION=3.2.56 bash
Downloading SST ❍ ion version: 3.2.56 ...
######################################################################## 100.0%

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Was going to push a PR just changing the repo in the install script but would break peoples CI if they are pinned to a pre 3.2.41 version which is maybe fine? Or do something more complex and use the old ion repo if its a pre 3.2.41 version.

**Comment by thdxr** [comment]
i think it's fine to break - thank you!

**Comment by aatecey** [comment]
PR for this: https://github.com/sst/sst/pull/4976
