### ISSUE TITLE
[ION-1431] examples: internal load balancer and load balancer vpc link

### ISSUE THREAD

**Issue by fwang** [anomalyco/sst#4987]
- https://github.com/sst/sst/tree/dev/examples/aws-cluster-internal
- https://github.com/sst/sst/tree/dev/examples/aws-cluster-vpclink

For the internal ALB endpoint, we can show that the endpoint will hang if curled directly. But works if curl'ed from the bastion host:
```bash
aws ssm start-session --target ${vpc.bastion}
curl ...
```

<sub>[ION-1431](https://linear.app/sst-dev/issue/ION-1431/examples-internal-load-balancer-and-load-balancer-vpc-link)</sub>

**Comment by jayair** [comment]
done
