### ISSUE TITLE
help: Setup sst config PNPM workspace setup using Docker

### ISSUE THREAD

**Issue by EmilEinarsen** [anomalyco/sst#4992]
I started looking into how to deploy this template: [remix-gospel-stack](https://github.com/PhilDL/remix-gospel-stack/tree/main). 

Wanted to tryout deploying it to AWS using SST v3.

I can't seem to get "apps/remix-app" to play nicely once deployed successfully, jut get a 502 error.

Any pointers would be much appreciated

**Comment by jayair** [comment]
Can I see your sst config?

**Comment by EmilEinarsen** [comment]
Thank you for getting back to me.
I finally got everything working. Loving SST IaC!

I got one question that I couldn't find the answer to:
In the deployment workflow, is there a way to set secrets to all PR stages? 
Like "sst secret set [property] [value] --stage pr-*"

**Comment by jayair** [comment]
You can use fallbacks https://sst.dev/docs/reference/cli#secret

I'll close this for now. Feel free to open a separate issue.

**Comment by EmilEinarsen** [comment]
That's awesome, thank you!
