### ISSUE TITLE
NextJS w/Prisma on Docker missing DATABASE_URL env var during npm run build

### ISSUE THREAD

**Issue by himanchau** [anomalyco/sst#4993]
Tried combining the Prisma and NextJS examples with deploying via Docker. During the build phase, Prisma needs access to the interpolated DATABASE_URL, but there's no documentation showing how to link the env variable in Docker.

sst.config.ts
```
const rds = new sst.aws.Postgres("PlatformRDS", { vpc, proxy: true });
const DATABASE_URL = $interpolate`postgresql://${rds.username}:${rds.password}@${rds.host}:${rds.port}/${rds.database}`;

const cluster = new sst.aws.Cluster("PlatformCluster", { vpc });

cluster.addService("NextProd", {
      environment: { DATABASE_URL },
      link: [staticBucket, fileBucket],
      public: {
        ports: [{ listen: "80/http", forward: "3000/http" }],
      },
});
```

Dockerfile
```
...
FROM base as builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build
...
```

Fails during the build process:
```
...
 ✓ Collecting page data    
   Generating static pages (0/14)  [    ]prisma:error 
Invalid `prisma.user.findMany()` invocation:


error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:10
...
```

I've tried linking with but that does not work.
```
# Add linked resources to the environment
ARG SST_RESOURCE_PlatformRDS
```

What am I missing here?

Thanks.

**Comment by himanchau** [comment]
Getting this as well during Docker build:
```
Error: It does not look like SST links are active. If this is in local development and you are not starting this process through the multiplexer, wrap your command with `sst dev -- <command>
```

**Comment by jayair** [comment]
I'll need to try this out but the issue here is that Next.js is trying to build your pages inside Docker, so it'll need a couple of things:

- The DATABASE_URL has to be added the same way the SST_RESOURCE_* env var is added
- You'll most likely need `sst tunnel` running if it's going to query the db

**Comment by himanchau** [comment]
Got it. I will try it out. It's having the same issue with the Linked buckets. During build time in Docker, it cannot access the bucket names.

**Comment by himanchau** [comment]
Needed the tunnel to build pages. Was able to pass the `DATABASE_URL` using args in the `cluster.addService`

```
image: {
  args: {
    DATABASE_URL,
  },
},
```
