### ISSUE TITLE
sst.aws.Vpc.get() fails with "resource '/sst/vpc/vpc-{id}/private-key' does not exist" on deploy

### ISSUE THREAD

**Issue by aatecey** [anomalyco/sst#4998]
sst version 3.2.70
Was attempting to spin up a stage hanging off a VPC in our dev account and have started encountering this error on deploy:

|  Error       KindledPrivateKey aws:ssm:Parameter
|  resource '/sst/vpc/vpc-{id}/private-key' does not exist

The VPC is using ec2 nats and I never enabled bastion.

```typescript
export const vpc = isPermanentStage($app.stage)
  ? new sst.aws.Vpc("Kindled", {
      az: isProduction($app.stage) ? 3 : 2,
      nat: isProduction($app.stage) ? "managed" : "ec2",
      transform: {
        vpc: {
          cidrBlock: CIDR_BLOCK,
        },
      },
    })
  : sst.aws.Vpc.get("Kindled", "vpc-{id}");
```

Within the sst vpc component bastionInstance always is defined for me here so its goes to make a request to ssm:
```typescript
    const privateKeyValue = bastionInstance.apply((v) => {
      if (!v) return;
      const param = ssm.Parameter.get(
        `${name}PrivateKey`,
        interpolate`/sst/vpc/${vpc.id}/private-key`,
        undefined,
        opts,
      );
      return param.value;
    });
```

Related commit: https://github.com/sst/sst/commit/fe2f41cbfb9632a3277cceb02414d1bd37fbc219

**Comment by msfstef** [comment]
Running into the same issue here with sst `3.2.56` and aws `6.57.0`

**Comment by felix-xeel** [comment]
Just hit this too, after upgrading to `3.3.6` - I'm going to 'un-borrow' the dev VPC and just spin up another to work-around this for now.

**Comment by fwang** [comment]
Releasing v3.3.9 with [the fix](https://github.com/sst/sst/commit/b18bf7bb6191cf01da658b9f93d05a2eab277635).

After u update, make sure to deploy the stage where the Vpc is created (ie. `new sst.aws.Vpc()`) first, and then deploy the stage referencing it.

Please reopen if issue persists.
