### ISSUE TITLE
Remix deployment on serverless results on just downloading the page

### ISSUE THREAD

**Issue by jjdp** [anomalyco/sst#4999]
Following the guide at [https://sst.dev/docs/start/aws/remix](https://sst.dev/docs/start/aws/remix) on Serverless. The app deployed on cloudfront just straight up downloads the page with an empty file.

Remix's template starter is not that different from the example repo [https://github.com/sst/sst/tree/dev/examples/aws-remix](https://github.com/sst/sst/tree/dev/examples/aws-remix)

`"@remix-run/node": "^2.13.1",
    "@remix-run/react": "^2.13.1",
    "@remix-run/serve": "^2.13.1",`
`"vite": "^5.1.0",`

Deploying the app under containers seems to be fine though.

**Comment by jayair** [comment]
Can you try deploying the one from the repo? Do you see the same thing?

**Comment by jjdp** [comment]
> Can you try deploying the one from the repo? Do you see the same thing?

Same download behavior

**Comment by usama-m98** [comment]
I've had the same issue before, but it was caused by no loader being configure for .node files from a 3rd party package, are you using any other dependencies?

**Comment by jayair** [comment]
I just updated https://github.com/sst/sst/tree/dev/examples/aws-remix to Remix 2.15 and tested deploying it. It worked.

<img width="1292" alt="Screenshot 2024-11-23 at 4 43 33 PM" src="https://github.com/user-attachments/assets/edd4d9be-b67a-42fe-b2e3-19dd4f2cf1b9">
