### ISSUE TITLE
Environment Variable not Loading in Local Execution of Lambda Function

### ISSUE THREAD

**Issue by jmoliugp** [anomalyco/sst#5001]
## Description

I am experiencing an issue with a Lambda function in my SST project. While the environment variable `USER_TABLE` is correctly set and visible in the AWS console after deployment, it does not seem to load when executing the function locally.

### Steps to Reproduce
1. Set up the SST project and define an environment variable in the proper stack.
2. Deploy the stack to AWS and verify that the environment variable is present in the AWS Lambda console.
3. Attempt to run the Lambda function locally using `npx sst start`.
4. Check the logs or output to confirm that the `USER_TABLE` variable is not loaded.

### Expected Behavior
The  environment variable should be accessible within the local execution context of the Lambda function, similar to how it is available in the deployed version.

### Actual Behavior
The environment variable is not available during local execution, leading to potential errors when the function attempts to access it.

### Additional Information
- SST version: `2.43.4`
- Node.js version: `18`

### Code Snippets
Here are relevant code snippets for context:

**Stack Definition:**
```typescript
export function MyStack({ stack }: StackContext) {
  const { tableNames } = use(AppSyncApi);

  const myLambdaFunction = new Function(stack, "MyLambdaFunction", {
    handler: "packages/functions/src/myLambda.handler",
    environment: {
      USER_TABLE: tableNames["MyUserTableName"],
    },
    permissions: ["dynamodb"],
  });
}
```

**Lambda Function:**
```typescript
export const handler = async (event: any): Promise<void> => {
  const userTable = process.env.USER_TABLE;

  if (!userTable) {
    console.error("USER_TABLE environment variable is not set.");
    throw new Error("Missing USER_TABLE environment variable.");
  }

  // Function logic here...
};
```

**Comment by zammitjames** [comment]
Seems like you're running SST V2. This repository is for V3. You should open up an issue over [here](https://github.com/sst/v2/issues).

**Comment by jayair** [comment]
closing for now
