### ISSUE TITLE
Trouble connecting to RDS Postgres via sst dev in a local container

### ISSUE THREAD

**Issue by bitcoinski** [anomalyco/sst#5002]
I've been staring at this for a couple of days and could use a second set of eyes.

- Objective: Deploy Hasura as a container connected to Postgres
- Issue: When running sst dev I launch a local docker container for Hasura via dev.command since sst dev doesn't run containers locally. This local docker container can not connect to Postgres instance. I'm not sure how best to proceed, public subnet attached to the DB or vpc?

`

export const vpc = new sst.aws.Vpc(process.env.AWS_VPC_NAME, {
  bastion: true,
  nat: {
    ec2: {
      instance: "t4g.nano"
    }
  }
});

export const cluster = new sst.aws.Cluster(process.env.AWS_CLUSTER_NAME, { vpc });

const service = cluster.addService(process.env.HASURA_SERVICE_NAME, {
    scaling: {
      min: 1,
      max: 1,
      cpuUtilization: 75,
      memoryUtilization: 75,
    },
    // @ts-ignore
    cpu: process.env.HASURA_SERVICE_CPU,
    // @ts-ignore
    memory: process.env.HASURA_SERVICE_MEMORY,
    link: [],
    containers: [
      {
        name: `hasura-server`,
        image: "hasura/graphql-engine:v2.44.0.cli-migrations-v3",
        environment: await getEnvironmentVars(),
        dev: {
          command: "./infra/services/hasura/dev.sh",
          autostart: true,
        },
      }
    ]
  });

//nasty but works
async function getDatabaseUrl() {
  const dburl = database.database.apply(dbname =>
    database.username.apply(username =>
      database.password.apply(password =>
        database.host.apply(host =>
          database.port.apply(port => {
            return `postgresql://${username}:${password}@${host}:${port}/${dbname}?sslmode=require`;
          })
        )
      )
    )
  );

  return dburl; 
}

// Function to get environment variables using apply
async function getEnvironmentVars() {
  const dbUrl = await getDatabaseUrl();
  
  // Use .apply() to handle the SST Output value
  return dbUrl.apply(url => {
    const vars = {
      APP_NAME: process.env.APP_NAME,
      HASURA_GRAPHQL_METADATA_DATABASE_URL: url,
      HASURA_GRAPHQL_DATABASE_URL: url,
      HASURA_GRAPHQL_ENABLE_CONSOLE: process.env.HASURA_GRAPHQL_ENABLE_CONSOLE,
      HASURA_GRAPHQL_DEV_MODE: process.env.HASURA_GRAPHQL_DEV_MODE,
      HASURA_GRAPHQL_ADMIN_SECRET: process.env.HASURA_GRAPHQL_ADMIN_SECRET,
      HASURA_GRAPHQL_SERVER_PORT: "8080",
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: "startup, http-log, webhook-log, websocket-log, query-log",
      HASURA_GRAPHQL_CORS_DOMAIN: "*",
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false",
      HASURA_GRAPHQL_PG_CONNECTIONS: "50",
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "public",
      HASURA_GRAPHQL_MIGRATIONS_SERVER_PORT: "9693",
      HASURA_GRAPHQL_MIGRATIONS_DIR: "/hasura-migrations",
      HASURA_GRAPHQL_METADATA_DIR: "/hasura-metadata",
      HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT_SECONDS: "180",
      HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT: "180",
      HASURA_GRAPHQL_ENDPOINT:`http://${process.env.APP_NAME}-hasura-server:8080`,
      HASURA_GRAPHQL_CONSOLE_PORT: "9695",
      HASURA_GRAPHQL_API_PORT: "9693",
      HASURA_GRAPHQL_CONSOLE_HGE_ENDPOINT: "http://localhost:8080",
    };

    const envContent = Object.entries(vars)
      .map(([key, value]) => `export ${key}="${value}"`)
      .join('\n');

   //write the envs to .env.generated so the .sh script can read them when docker run
    if($app.stage !== "staging" && $app.stage !== "production") {
      utils.writeFileSync("./infra/services/hasura/.env.generated", envContent);
    }

    return vars;
  });
}

`

dev.sh

`
#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source $SCRIPT_DIR/.env.generated

docker network create $APP_NAME-dev-network 2>/dev/null || true

docker rm -f $APP_NAME-hasura-server $APP_NAME-hasura-console 2>/dev/null || true

echo "Starting Hasura server..."

docker run -d \
  --name "$APP_NAME-hasura-server" \
  --network $APP_NAME-dev-network \
  -p "8080:8080" \
  -v "$SCRIPT_DIR/migrations:/hasura-migrations" \
  -v "$SCRIPT_DIR/metadata:/hasura-metadata" \
  -v "$SCRIPT_DIR/seeds:/hasura-seeds" \
  -v "$SCRIPT_DIR/config.yaml:/etc/hasura/config.yaml" \
  -e HASURA_GRAPHQL_METADATA_DATABASE_URL="$HASURA_GRAPHQL_METADATA_DATABASE_URL" \
  -e HASURA_GRAPHQL_DATABASE_URL="$HASURA_GRAPHQL_DATABASE_URL" \
  -e HASURA_GRAPHQL_ENABLE_CONSOLE="$HASURA_GRAPHQL_ENABLE_CONSOLE" \
  -e HASURA_GRAPHQL_DEV_MODE="$HASURA_GRAPHQL_DEV_MODE" \
  -e HASURA_GRAPHQL_ADMIN_SECRET="$HASURA_GRAPHQL_ADMIN_SECRET" \
  -e HASURA_GRAPHQL_UNAUTHORIZED_ROLE="public" \
  -e HASURA_GRAPHQL_SERVER_PORT="8080" \
  -e HASURA_GRAPHQL_ENABLED_LOG_TYPES="startup, http-log, webhook-log, websocket-log, query-log" \
  -e HASURA_GRAPHQL_CORS_DOMAIN="*" \
  -e HASURA_GRAPHQL_ENABLE_TELEMETRY="false" \
  -e HASURA_GRAPHQL_PG_CONNECTIONS="50" \
  -e HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT="180" \
  -e HASURA_GRAPHQL_MIGRATIONS_SERVER_PORT="9693" \
  -e HASURA_GRAPHQL_MIGRATIONS_DIR="/hasura-migrations" \
  -e HASURA_GRAPHQL_METADATA_DIR="/hasura-metadata" \
  "hasura/graphql-engine:v2.44.0.cli-migrations-v3" || {
    echo "Error: Hasura Server container failed to start"
    exit 1
  }

echo "Waiting for Hasura server to be ready..."
until curl -s http://localhost:8080/healthz > /dev/null; do
  sleep 1
done

echo "Hasura server is ready"

echo "Starting Hasura console..."

docker run -d \
  --name "$APP_NAME-hasura-console" \
  --network $APP_NAME-dev-network \
  -p "9695:9695" \
  -p "9693:9693" \
  -v "$SCRIPT_DIR:/hasura" \
  -w "/hasura" \
  -e HASURA_GRAPHQL_METADATA_DATABASE_URL="$HASURA_DB_URL" \
  -e HASURA_GRAPHQL_DATABASE_URL="$HASURA_DB_URL" \
  -e HASURA_GRAPHQL_ADMIN_SECRET="$HASURA_GRAPHQL_ADMIN_SECRET" \
  -e HASURA_GRAPHQL_ENABLED_LOG_TYPES="startup, http-log, webhook-log, websocket-log, query-log" \
  -e HASURA_GRAPHQL_ENDPOINT="http://$APP_NAME-hasura-server:8080" \
  -e HASURA_GRAPHQL_CONSOLE_PORT="9695" \
  -e HASURA_GRAPHQL_API_PORT="9693" \
  -e HASURA_GRAPHQL_CONSOLE_HGE_ENDPOINT="http://localhost:8080" \
  "hasura/graphql-engine:v2.44.0.cli-migrations-v3" \
  hasura-cli console \
  --no-browser \
  --endpoint "http://$APP_NAME-hasura-server:8080" \
  --admin-secret "$HASURA_GRAPHQL_ADMIN_SECRET" \
  --address "0.0.0.0" \
  --console-port "9695" \
  --api-port "9693" \
  --console-hge-endpoint "http://localhost:8080" || {
    echo "Error: Hasura Console container failed to start"
    docker logs hasura_console
    exit 1
  }

echo "Waiting for Hasura console to be ready..."
until curl -s http://localhost:9695 > /dev/null; do
  sleep 1
done

echo "Hasura console is ready"

if command -v xdg-open &> /dev/null; then
    xdg-open "http://localhost:9695"
elif command -v open &> /dev/null; then
    open "http://localhost:9695"
elif command -v start &> /dev/null; then
    start "http://localhost:9695"
fi

tail -f /dev/null
`

**Comment by zammitjames** [comment]
Is the database accessible from your local machine outside of your code when your tunnel is running? Ex: Using `tableplus` or something like `drizzle studio`? I'd also try disable ssl in the connection string if not.

**Comment by bitcoinski** [comment]
Ooof, looks like it was a local firewall/vpn issue. Can connect now via tunnel. Thanks for the sanity check @zammitjames

**Comment by zammitjames** [comment]
Ah - nice find! I actually had a similar issue last week. The wifi I was connected to (old unifi gateway) just blocked the tunnel completely.

**Comment by bitcoinski** [comment]
@zammitjames quick follow up question. On startup it seems the container attempts to connect to the db before the tunnel is ready, if I restart the container after a few seconds it can then connect since the tunnel is listening at that point. Is there a way to await the tunnel before starting the container that you know of? If not I might pop it into the .sh file that launches docker

**Comment by zammitjames** [comment]
Hmm interesting - I haven't run into that - can you increase the connection timeout or retry amount while in the $dev stage maybe? Like that your app would hopefully establish a connection at the second or third retry attempt.

Otherwise a trivial/naive way might be to add a `sleep(5000)` while in dev.

**Comment by bitcoinski** [comment]
@zammitjames figured out a solution, I check for the tunnel to be open before launching the local containers in my .sh file:

`# Function to check if SST tunnel is ready by attempting a PostgreSQL connection
check_tunnel() {
    # Try to connect to PostgreSQL using psql or pg_isready
    if command -v pg_isready &> /dev/null; then
        pg_isready -h "$DB_HOST" -p "$DB_PORT" &> /dev/null
        return $?
    else
        # Fallback to basic TCP check
        timeout 1 bash -c "</dev/tcp/$DB_HOST/$DB_PORT" &> /dev/null
        return $?
    fi
}

# Function to wait for tunnel with timeout
wait_for_tunnel() {
    echo "Waiting for SST tunnel to be ready..."
    local timeout=60  # timeout in seconds
    local start_time=$(date +%s)
    
    while ! check_tunnel; do
        local current_time=$(date +%s)
        local elapsed=$((current_time - start_time))
        
        if [ $elapsed -ge $timeout ]; then
            echo "Timeout waiting for tunnel after ${timeout} seconds"
            return 1
        fi
        
        echo "Waiting for database connection... (${elapsed}s)"
        sleep 2
    done
    echo "SST tunnel is ready!"
}

# Add timeout handling
if ! wait_for_tunnel; then
    echo "Failed to establish database connection. Please check if SST tunnel is running correctly."
    exit 1
fi`

**Comment by bitcoinski** [comment]
Thanks again

**Comment by bitcoinski** [comment]
Thanks again
