### ISSUE TITLE
sst dev doesn't seem to respect .npmrc file

### ISSUE THREAD

**Issue by tbehunin** [anomalyco/sst#5006]
I'm following the SST guide step-by-step - currently here: https://guide.sst.dev/chapters/create-a-hello-world-api.html. Running:
```
$ npx sst dev
```
and it gets stuck "Installing providers...". Here's my current log file:
```
time=2024-10-31T14:55:26.678-07:00 level=INFO msg="checking for pulumi" path="/Users/tbehunin/Library/Application Support/sst/bin/pulumi"
time=2024-10-31T14:55:26.918-07:00 level=INFO msg="initializing project" version=3.2.70
time=2024-10-31T14:55:26.919-07:00 level=INFO msg="esbuild building" out=/Users/tbehunin/code/myproj-sst/.sst/platform/sst.config.1730411726919.mjs
time=2024-10-31T14:55:26.928-07:00 level=INFO msg="esbuild built" outfile=/Users/tbehunin/code/myproj-sst/.sst/platform/sst.config.1730411726919.mjs
time=2024-10-31T14:55:26.928-07:00 level=INFO msg="evaluating config"
time=2024-10-31T14:55:26.958-07:00 level=INFO msg="config evaluated"
time=2024-10-31T14:55:26.961-07:00 level=INFO msg="checking platform"
time=2024-10-31T14:55:26.961-07:00 level=INFO msg="installing deps"
time=2024-10-31T14:55:26.961-07:00 level=INFO msg="getting package" name=@sst-provider/aws version=latest
time=2024-10-31T14:55:29.362-07:00 level=INFO msg="getting package" name=@pulumi/aws version=latest
time=2024-10-31T14:55:29.501-07:00 level=INFO msg="writing package.json"
time=2024-10-31T14:55:29.502-07:00 level=INFO msg="adding dependency" name=aws
time=2024-10-31T14:55:29.503-07:00 level=INFO msg="fetching deps"
```
After waiting long enough, I get a network error in the logs and a URL it attempted to query from which happened to be my corporate npm repository. I tried to resolve it by adding a `.npmrc` file with the following contents:
```
registry=https://registry.npmjs.org/
```
But even with that, it still doesn't respect it and attempts to pull from my corporate repository. I thought my machine may be configured to use a proxy server but when I go to System Settings > Network > select the network and then Details > Proxies, nothing is turned on. It must be some sort of config I need to switch but not sure what. Any ideas on how to fix this?

OS: MacOS Sequoia 15.0.1
Node: 20 or 22 something

**Comment by jayair** [comment]
Yeah we are not reading from the .npmrc but we do have this:

<img width="618" alt="Screenshot 2024-11-01 at 5 54 24 PM" src="https://github.com/user-attachments/assets/f45d33f2-1b5c-4859-b408-3f3baef843f2">

https://sst.dev/docs/reference/cli#add

**Comment by tbehunin** [comment]
@jayair Thanks for this! I figured out the issue on my machine: I had an `.npmrc` file at the root of my user folder (`~/.npmrc`) that had my corporate npm registry url. It appears `sst` respects that file and not the one in the project folder - which is fine once I understood what was happening. Once I changed the registry in `~/.npmrc` to the npm public url, everything worked!
