### ISSUE TITLE
Docs: EFS with `sst dev`

### ISSUE THREAD

**Issue by ezg27** [anomalyco/sst#5009]
This may be expected at this stage as it looks like the EFS component was only shipped recently, but I can't find anything in the docs mentioning that local development isn't supported in this case.

Steps to reproduce:

1. clone down the `aws-efs-sqlite` example from the sst repo
2. install deps with package manager of your choice
3. run `sst dev`
4. resources will deploy successfully
5. attempt to access deployment url
6. response will hang in the browser, eventually returning 500 response with text `it does not seem like sst dev is running`
7. the `Functions` tab in the terminal will log out `Cannot open database because the directory does not exist` where `better-sqlite3` attempts to create the database file at `/mnt/efs` (attempting to stat `/mnt/efs` directly will also return `ENOENT: no such file or directory, stat '/mnt/efs'`)
8. checking in the AWS console, all resources appear to be successfully created and linked (i.e. Lambda, local mount path, filesystem accesspoint etc)

From looking at other examples using Lambda with VPCs, it looks as though the new sst tunnel may be required to use private resources alongside functions with `sst dev` - however, I still get the same errors after installing the tunnel and setting `bastion: true` via the `VPC` constructor in `sst.config.ts`.

For context, when running `sst deploy` and accessing the deployed function url things work perfectly. However, the `sst dev` errors appear to be common to all 3 EFS examples.

Is this likely a bug, or is the EFS component not supported with `sst dev` at this time?

Many thanks!

**Comment by jayair** [comment]
Yeah I'll mention this in the docs but your Lambda function (or container) running locally does not have access to EFS. The assumption is that you are using the local filesystem.

**Comment by ezg27** [comment]
Ahh apologies that's mainly me misunderstanding where things were running during `sst dev` 🤦‍♂️

Many thanks for the quick response! I've got things running now using some conditional logic keyed from `process.env.SST_LIVE`.
