### ISSUE TITLE
Package allowlist/blocklist in monorepo mode

### ISSUE THREAD

**Issue by user-0a** [anomalyco/sst#5011]
We're migrating a large codebase over to SST. We figured we would start with monorepo mode and configure it to only manage a few of our resources at first, and then incrementally adopt it for more of our stack over time.

It looks like the CLI creates `sst-env.d.ts` files in all of our the packages in our repo. This includes:
- Packages for resources not managed by SST
- Tons of one-off scripts (which we create separate packages for under a collective `scripts` directory)

This is a minor issue but just thought I would mention it.

**Comment by jayair** [comment]
Yeah we might have an open issue for this.

**Comment by user-0a** [comment]
Ahh I missed it, apologies!

Closing now, this is a duplicate of https://github.com/sst/sst/issues/4104
