### ISSUE TITLE
Load balancer HTTP to HTTPS

### ISSUE THREAD

**Issue by valerarusu7** [anomalyco/sst#5019]
Hi, I am using the default template for the next js app deploying it to Fargate.

Having these 2 options in the load balancer, how should I redirect all the traffic from http to https?

`{ listen: "80/http", forward: "3000/http" },
{ listen: "443/https", forward: "3000/http" }
`

**Comment by AlbertoV5** [comment]
Was wondering the same thing. This seems to work for v3:
```
import * as aws from "@pulumi/aws"

...

const service = cluster.addService(...)
const loadBalancer = service.nodes.loadBalancer
const listener = new aws.lb.Listener("http-listener", {
  loadBalancerArn: loadBalancer.arn,
  port: 80,
  protocol: "HTTP",
  defaultActions: [
    {
      type: "redirect",
      redirect: {
        port: "443",
        protocol: "HTTPS",
        statusCode: "HTTP_301",
      },
    },
  ],
})
```
Requires: `@pulumi/aws`

Source: 
- https://www.pulumi.com/registry/packages/aws/api-docs/alb/listener/#redirect-action
- https://www.pulumi.com/ai/answers/j6DXUP97YFSDWgJzCxo2Y4/configuring-aws-load-balancer-for-http-to-https-redirection

**Comment by valerarusu7** [comment]
> Was wondering the same thing. This seems to work for v3:
> 
> ```
> import * as aws from "@pulumi/aws"
> 
> ...
> 
> const service = cluster.addService(...)
> const loadBalancer = service.nodes.loadBalancer
> const listener = new aws.lb.Listener("http-listener", {
>   loadBalancerArn: loadBalancer.arn,
>   port: 80,
>   protocol: "HTTP",
>   defaultActions: [
>     {
>       type: "redirect",
>       redirect: {
>         port: "443",
>         protocol: "HTTPS",
>         statusCode: "HTTP_301",
>       },
>     },
>   ],
> })
> ```
> 
> Requires: `@pulumi/aws`
> 
> Source:
> 
> * https://www.pulumi.com/registry/packages/aws/api-docs/alb/listener/#redirect-action
> * https://www.pulumi.com/ai/answers/j6DXUP97YFSDWgJzCxo2Y4/configuring-aws-load-balancer-for-http-to-https-redirection

Interesting, I will give this a go. Thank you!

**Comment by jayair** [comment]
I might be wrong but we automatically do this if you use a custom domain.

**Comment by valerarusu7** [comment]
> I might be wrong but we automatically do this if you use a custom domain.

I am using a custom domain.

From what I can see, the http can still be accessed. Maybe there is a configuration that I am missing?

**Comment by jayair** [comment]
Let me check.

**Comment by fwang** [comment]
Added support in v3.3.23.

ie.
```ts
ports: [
  { listen: "80/http", redirect: "443/https" },
  { listen: "443/https", forward: "80/http" }
]
```

**Comment by valerarusu7** [comment]
> Added support in v3.3.23.
> 
> ie.
> 
> ```ts
> ports: [
>   { listen: "80/http", redirect: "443/https" },
>   { listen: "443/https", forward: "80/http" }
> ]
> ```

Amazing <3 This was exactly what I tried to do as well but everything failed. Thanks a lot :)
