### ISSUE TITLE
Expected an ID aws:sesv2:ConfigurationSet  

### ISSUE THREAD

**Issue by harrycollin** [anomalyco/sst#5020]
Something introduced in version `v3.2.32` is blocking me from upgrading my project currently stuck on `v3.2.26.`. 

I get the following error when running `yarn sst dev`. 

```
✕  Failed                                                                                                                                                                                               
│  MyEmailConfig aws:sesv2:ConfigurationSet                                                                                                                                                             
│  Expected an ID for urn:pulumi:harry::my-app::aws:sesv2/configurationSet:ConfigurationSet::MyEmailConfig
```

My SST config defines an email like so: 

```
const email =
      $app.stage !== "production"
        ? sst.aws.Email.get("MyEmail", "mydomain.com")
        : new sst.aws.Email("MyEmail", {
            sender: "mydomain.com",
            dns: false,
          });
```

Any ideas how I can migrate to the latest CLI? Thanks

**Comment by jayair** [comment]
Can you try the latest?

**Comment by harrycollin** [comment]
Just tried with v3.3.10 and receive the same error

**Comment by fwang** [comment]
@harrycollin can u try deploying the stage `Email` was created in first (ie. `new sst.aws.Email`). And then redeploy the stage referencing `Email`.

**Comment by suhascv** [comment]
I have the same issue 
@fwang I also tried to redeploy the email to production stage with `new sst.aws.Email`, no issue on production stage
but still getting the above mentioned error on `sst dev`

**Comment by harrycollin** [comment]
I can confirm I experience the same behaviour that @suhascv reported

**Comment by harrycollin** [comment]
@fwang I've just tried with `v3.2.20` and it seems to work now. Thank you!
