### ISSUE TITLE
AWS Cognito: Invalid MFA configuration given

### ISSUE THREAD

**Issue by WayneBuckhanan** [anomalyco/sst#5022]
```
✕  Failed    
   UserPool sst:aws:CognitoUserPool → UserPoolUserPool aws:cognito:UserPool
     sdk-v2/provider2.go:520: sdk.helper_schema: setting Cognito User Pool (us-east-1_...) MFA configuration: operation error Cognito Identity Provider: SetUserPoolMfaConfig, https response error StatusCode: 400, RequestID: 71d38a30-c519-4d9f-9c65-b8850d691caa, InvalidParameterException: Invalid MFA configuration given, can't turn off MFA and configure an MFA together.: provider=aws@6.57.0
```
Stepped versions of sst back from 3.2.76 and was able to successfully redeploy an existing project with 3.2.73.

Don't have the time to dig into it myself this week, but opening the ticket so y'all know about the issue.  Will work on it next week if still open.

**Comment by w5mix** [comment]
```
Failed    
   UserPool sst:aws:CognitoUserPool → UserPoolUserPool aws:cognito:UserPool
     sdk-v2/provider2.go:520: sdk.helper_schema: setting Cognito User Pool (us-east-1_....) MFA configuration: operation error Cognito Identity Provider: SetUserPoolMfaConfig, https response error StatusCode: 400, RequestID: 425efdd9-8050-439d-9495-c57c43b0778a, InvalidParameterException: Invalid MFA configuration given, can't turn off MFA and configure an MFA together.: provider=aws@6.57.0
```

Also seeing it.   Fresh deploy works fine, but subsequent deploys show this error.

**Comment by juanmguzmann** [comment]
Same issue, upgraded from a previous sst version and this started happening. Downgrading to 3.2.23 for now.

**Comment by thelegendtubaguy** [comment]
I upgraded to `3.3.3` and started experiencing this.  I downgraded to `3.2.73` and the issue resolved.  

Looks related to https://github.com/sst/sst/pull/4995

I think that change made it so the `softwareTokenMfaConfiguration` block is always defined, but we can't have it be defined if `mfaConfiguration` is `off`.
```ts
softwareTokenMfaConfiguration: args.softwareToken && {
  enabled: true,
},
```
vs
```ts
softwareTokenMfaConfiguration: output(args.softwareToken).apply(
  (v) => ({
    enabled: v ?? false,
  }),
),
```

**Comment by thelegendtubaguy** [comment]
@thdxr Could we get this looped in to a release soon?  This makes the 3.3 versions difficult to use if you're utilizing `CognitoUserPool`

**Comment by jakubknejzlik** [comment]
FYI version 3.2 seems to be affected as well (from [v3.2.74](https://github.com/sst/sst/releases/tag/v3.2.74), just switched back to [v3.2.73](https://github.com/sst/sst/releases/tag/v3.2.73) and works ok)
