### ISSUE TITLE
Feature Request: support the --target param when specifying a image for a service in a Cluster

### ISSUE THREAD

**Issue by bitfrost** [anomalyco/sst#5032]
Currently build-args are exposed but for those of us managing 'clever' multi-stage docker files exposing --target would be useful.
https://docs.docker.com/build/building/multi-stage/#stop-at-a-specific-build-stage 
(My particular use case, 1 docker file that manages a bunch of shared build steps (think mono repo) and also has several layers for several deployable images (like a  next.js server post build).

**Comment by jayair** [comment]
You are saying exposing the `--target` on top of the build args? https://sst.dev/docs/component/aws/cluster#image-args

**Comment by bitfrost** [comment]
Yep (unless I am missing something) currently SST build-args build-args map to https://docs.docker.com/build/building/variables/#build-arguments
Which is not something that maps to a target name in a multi stage Dockerfile
--target is how you set that name if not Docker building "all" of the layers (last one winning). 
 From docker docs:
 
  Note

In your multi-stage Dockerfile, the final stage (final) is the default target for building. This means that if you don't explicitly specify a target stage using the --target flag in the docker build command, Docker will automatically build the last stage by default. You could use docker build -t spring-helloworld-builder --target builder . to build only the builder stage with the JDK environment.

https://docs.docker.com/get-started/docker-concepts/building-images/multi-stage-builds/

**Comment by roninjin10** [comment]
I'm running into this issue too. I normally build my entire monorepo and then have many stages after the monorepo is built that build individual services. My dockerfile won't work with sst because I can't use --target

**Comment by jayair** [comment]
Yeah we should support this @fwang

**Comment by fwang** [comment]
Added in v3.4.37.

```ts
cluster.addService("MyService", {
  image: {
    target: "build",
  },
});
```
