### ISSUE TITLE
How can I disable/enable a cron schedule?

### ISSUE THREAD

**Issue by joao-vitor-felix** [anomalyco/sst#5037]
I need to run two crons, one to perform a **disbursement retry** the whole night if I'm not successful doing it, but disable it for the night as soon as everything have worked fine, and the other one to **enable disbursement retry** back the following day if it was disabled the previous night.

As far as I've searched, to do it, I need to define a rule so I can perform these operations, but I don't know how to do it, here's my crons definitions alongside the enable cron:

```ts
    new sst.aws.Cron('RetryFailedDisbursement', {
      job: {
        handler: `${rootDirectory}/retry-failed-disbursement/cron.handler`,
        environment,
        timeout: `${5} minute`,
      },
      transform: {
        rule: {
          name: 'RetryFailedDisbursementRule',
        },
      },
      schedule: 'cron(0 17-23 ? * 2-6 *)',
    })

new sst.aws.Cron('EnableDisbursementRetry', {
      job: {
        handler: `${rootDirectory}/enable-disbursement-retry/cron.handler`,
        environment,
        timeout: `${1} minute`,
        permissions: [
          {
            actions: ['*'],
            resources: ['*'],
          },
        ],
      },
      schedule: 'cron(50 19 ? * 2-6 *)',
    })
```

I used `transform.rule.name` to set a rule, but I not even sure if it is right. I also defined `permissions` as this 'cause I was having trouble with `resources`, I didn't know where I get the arn to put there, so `*` solved it temporarily.

```permissions: [
          {
            actions: ['*'],
            resources: ['*'],
          },
        ],
```

Enable cron:

```ts
import { eventBridge } from '@/_lib/event-bridge'

export const handler = async () => {
  console.info('Starting EnableDisbursementRetry cron...')
  console.info('Checking rule state...')

  const rule = await eventBridge.describeRule({
    Name: 'RetryFailedDisbursementRule',
  })

  console.info('Rule state:', rule.State)

  if (rule.State === 'ENABLED') {
    console.info('Rule is already enabled. Exiting...')
    return
  }

  console.info('Enabling rule...')

  await eventBridge.enableRule({
    Name: 'RetryFailedDisbursementRule',
  })

  console.info('Rule enabled!')
}
```

But I'm getting:

`Rule RetryFailedDisbursementRule does not exist on EventBus default.
|  ↳ ResourceNotFoundException: Rule RetryFailedDisbursementRule does not exist on EventBus default.`

So please, how can I proper set it up to disable the disbursement cron if needed and enable it if needed? 

If you could also clarify what can I put on `resources` from `permissions` would also be great. 

Thank you!

**Comment by jayair** [comment]
I haven't done this before but can you share a snippet of the code or a link to some other example where you've seen how to do this?

We can help you change that to work in SST.

**Comment by joao-vitor-felix** [comment]
Well, I searched for it on sst's doc last week, but I didn't find it, so I asked ChatGPT, I'll let the link for the answer below. But it does make sense since Cron uses Event Bus, and the doc says: 

"[Rules](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-rules.html) associated with the event bus evaluate events as they arrive. Each rule checks whether an event matches the rule's pattern. If the event does match, EventBridge sends the event"

"You can also create rules that sends events to the specified targets at specified intervals. For example, to periodically run a Lambda function, you can create a rule to run on a schedule."

"To stop a [rule](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-rules.html) from processing [events](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-events.html) or running on a schedule, you can delete or disable the rule. The following steps walk you through how to delete or disable an EventBridge rule."

Taking it under consideration, I think it is something that can be added to Cron component, and would be really valuable

[ChatGPT answer](https://chatgpt.com/share/6731f98b-10a4-8011-ae7c-ec50fd2d657c)
[Disabling or deleting a rule in Amazon EventBridge](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-delete-rule.html)
[Use DisableRule with an AWS SDK or CLI](https://docs.aws.amazon.com/eventbridge/latest/userguide/example_eventbridge_DisableRule_section.html)

If you need any further help, let me know! Thank you for your fast answer!

**Comment by jayair** [comment]
Yeah I'm not familiar with this. If you find a doc on this then we can take a look.

**Comment by joao-vitor-felix** [comment]
Got it, thank you so much!!
