### ISSUE TITLE
CDN `invalidation.paths` has a limit of 15 wildcards, but no clear error when it is surpassed

### ISSUE THREAD

**Issue by VersorVerbi** [anomalyco/sst#5040]
[pkg/server/resource/aws-distribution-invalidation.go](https://github.com/sst/sst/blob/ee81836c2481b0e3e132a8e4afed6d6158c2442c/pkg/server/resource/aws-distribution-invalidation.go) includes a `WILDCARD_LIMIT` of `15`, based on AWS' [confident request limit](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/InvalidationLimits.html). But if you include more than 15 wildcard paths in `invalidation.paths`, you don't get an error message about that, you just get an index-out-of-bounds panic:

```shell
panic: runtime error: slice bounds out of range [3000:1]

goroutine 1541 [running]:
github.com/sst/ion/pkg/server/resource.(*DistributionInvalidation).invalidate(0xc000d10178, 0xc0001bed00, 0xc000cdee00)
        /home/runner/work/sst/sst/pkg/server/resource/aws-distribution-invalidation.go:88 +0x690
github.com/sst/ion/pkg/server/resource.(*DistributionInvalidation).handle(0xc000d10178, 0xc000cdee00)
        /home/runner/work/sst/sst/pkg/server/resource/aws-distribution-invalidation.go:56 +0xdf
github.com/sst/ion/pkg/server/resource.(*DistributionInvalidation).Create(0x1?, 0x1?, 0xc001e12048)
        /home/runner/work/sst/sst/pkg/server/resource/aws-distribution-invalidation.go:32 +0x18
reflect.Value.call({0xc00019e6c0?, 0xc000d10198?, 0xc000bade18?}, {0x22cdef4, 0x4}, {0xc000badef8, 0x3, 0xc000b1d580?})
        /opt/hostedtoolcache/go/1.23.2/x64/src/reflect/value.go:581 +0xca6
reflect.Value.Call({0xc00019e6c0?, 0xc000d10198?, 0x50?}, {0xc000badef8?, 0x7f0144713a68?, 0x50?})
        /opt/hostedtoolcache/go/1.23.2/x64/src/reflect/value.go:365 +0xb9
net/rpc.(*service).call(0xc0002ee240, 0xc00001cd40, 0xc000ce0398, 0xc000ce03b0, 0xc000038c00, 0xc002dda020, {0x1dfaaa0?, 0xc000cdee00?, 0x84d1a5?}, {0x1e3b840, ...}, ...)
        /opt/hostedtoolcache/go/1.23.2/x64/src/net/rpc/server.go:381 +0x209
created by net/rpc.(*Server).ServeCodec in goroutine 1579
        /opt/hostedtoolcache/go/1.23.2/x64/src/net/rpc/server.go:478 +0x3d7
```

Surpassing this limit should generate a relevant error message.

**Comment by ifox** [comment]
This [page](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/InvalidationLimits.html), which is linked in the documentation page you shared, explains the limit: 

> If you’re using the * wildcard, you can have requests for up to 15 invalidation paths in progress at one time.

**Comment by VersorVerbi** [comment]
> This [page](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/InvalidationLimits.html), which is linked in the documentation page you shared, explains the limit: 
> 
> > If you’re using the * wildcard, you can have requests for up to 15 invalidation paths in progress at one time. 

Good find. No idea why that isn't more prominent. 
Updated the issue to focus on the missing error message.

**Comment by fwang** [comment]
This is a bug. SST should page through the wildcard paths and invalidate 15 at a time.

Fix will be in the next release.
