### ISSUE TITLE
Documentation: Managed NAT pricing is misleading

### ISSUE THREAD

**Issue by oskaerik** [anomalyco/sst#5043]
https://sst.dev/docs/component/aws/vpc#cost

https://github.com/sst/sst/blob/ee81836c2481b0e3e132a8e4afed6d6158c2442c/platform/src/components/aws/vpc.ts#L239

In the "EC2 NAT" section, the data transfer costs are mentioned. (0.09 USD/GB)

While the "Managed NAT" section only mentions the data processing charges (0.045 USD/GB). However, you also pay data transfer costs for the NAT Gateway (0.09 USD/GB). So in total, a more accurate number would be 0.135 USD/GB for the "Managed NAT".

From https://aws.amazon.com/vpc/pricing/:

> Data processing charges apply for each gigabyte processed through the NAT gateway regardless of the traffic’s source or destination. Each partial NAT Gateway-hour consumed is billed as a full hour. You also incur standard AWS data transfer charges for all data transferred via the NAT gateway.

**Comment by jayair** [comment]
Oh let me take a look.

**Comment by jayair** [comment]
Added a note on data transfer costs.
