### ISSUE TITLE
Support: The documentation lacks clarity regarding the process of creating Lambda layers.

### ISSUE THREAD

**Issue by nafishahmeddev** [anomalyco/sst#5062]
We have a large number of modules used by multiple Lambdas. Now we want to create a Lambda layer. However, the documentation doesn't provide instructions on creating a Lambda layer; it only covers attaching an existing layer.

**Comment by jayair** [comment]
Yeah I'll add an example for this. Tracking here https://github.com/sst/sst/issues/4532
