### ISSUE TITLE
Outdated setup instructions for SvelteKit

### ISSUE THREAD

**Issue by AlperSakarya** [anomalyco/sst#5067]
In this starter page [SvelteKit on AWS with SST](https://sst.dev/docs/start/aws/svelte), the initial step:
`npm create svelte@latest aws-svelte` is outdated. 

Users will receive` npm create svelte' has been replaced with 'npx sv create` and the directory will not be created.

It should be replaced with `npx sv create aws-svelte.
`

**Comment by jayair** [comment]
Yeah I'll take a look and update it.
