### ISSUE TITLE
404 links in the docs

### ISSUE THREAD

**Issue by AlperSakarya** [anomalyco/sst#5072]
The [Versioning](https://sst.dev/docs/components/#versioning) doc's Vpc and Vpc.1 links are goin to a 404...

These don't work which are linked:
[Vpc](https://sst.dev/docs/components/component/aws/vpc)
[Vpc.v1](https://sst.dev/docs/components/component/aws/vpc-v1)

**Comment by jayair** [comment]
Thanks. Fixed.
