### ISSUE TITLE
nodejs functions with arm64 external dependencies broken

### ISSUE THREAD

**Issue by cmanou** [anomalyco/sst#5080]
- If you try bundling sharp using  the following functionArgs
```
architecture: "arm64"
nodejs: {
install: ["sharp"]
}
```
It will install the x86_64 deps in the bundle. I believe the bug is caused via the payload passed via the RPC to go. Since go expects architecture to be part of the properties https://github.com/sst/sst/blob/bad21bf409eba1ed308aa2b89e0a8bb473b95e78/pkg/runtime/node/node.go#L115 but properties is just the nodejs args of the function https://github.com/sst/sst/blob/bad21bf409eba1ed308aa2b89e0a8bb473b95e78/platform/src/components/aws/function.ts#L1294 thus this never runs https://github.com/sst/sst/blob/bad21bf409eba1ed308aa2b89e0a8bb473b95e78/pkg/runtime/node/build.go#L273

**Comment by thdxr** [comment]
potentially fixed in v3.3.25

**Comment by cmanou** [comment]
Can confirm that that has fixed it
