### ISSUE TITLE
`sst upgrade` replaces any package.json entry matching `"sst": ...`

### ISSUE THREAD

**Issue by mgramigna** [anomalyco/sst#5098]
This issue is fairly niche and likely doesn't need to be highly prioritized, but flagging nonetheless.

if you have a `package.json` that has an entry for `"sst": "..."` elsewhere in addition to `dependencies` (e.g. in `scripts`), running `sst upgrade` will replace that entry with the latest version of sst. Here's a repo with reproduction steps: https://github.com/mgramigna/sst-packagejson-repro

Before running `bun sst upgrade`
```json
{
	"name": "sst-packagejson-repro",
	"module": "index.ts",
	"type": "module",
	"scripts": {
		"sst": "sst --"
	},
	"dependencies": {
		"sst": "3.3.27"
	}
}
```

After running `bun sst upgrade`
```json
{
	"name": "sst-packagejson-repro",
	"module": "index.ts",
	"type": "module",
	"scripts": {
		"sst": "3.3.27"
	},
	"dependencies": {
		"sst": "3.3.27"
	}
}
```

It's because [this regex](https://github.com/sst/sst/blob/613c1b2c86075ffd31e10ef334fce8f59c1b2a0d/pkg/global/upgrade.go#L125) is used in a replaceAll [here](https://github.com/sst/sst/blob/613c1b2c86075ffd31e10ef334fce8f59c1b2a0d/pkg/global/upgrade.go#L141). I doubt this really matters in the long run if you're using a global install of `sst` cli or running it with bunx/npx/etc. as there's no need for a scripts entry in that case, or you can just call it something different if you really want.

**Comment by jayair** [comment]
Oh we should fix this even if it's lower priority.

**Comment by mgramigna** [comment]
@jayair I’d be happy trying to get a PR up for it this weekend if you have a preferred approach otherwise can just leave it to y’all 

Edit: gave it a shot anyway

**Comment by jayair** [comment]
Thanks!
