### ISSUE TITLE
Deploying Cluster to Personal Stage -> Running SST Dev = Removal of all cluster elements from remote environment 

### ISSUE THREAD

**Issue by claridgicus** [anomalyco/sst#5100]
I'm new to SST so this could totally be an understanding problem.

I am creating a cluster and pushing up a dockerfile (chefs kiss, so easy)

Reproduction Steps

I run ```sst deploy```
-> My service appears perfectly, 200 response from my box, happy days
I then run ```sst dev```
--> SST then proceeds to happily delete all the running services on the remote and kinda hangs

Things you should know
- I've given SST admin access to my brand spanking new AWS account
- Nothing is overly special about my setup

For your reproducible pleasure
```
export default $config({
  app(input) {
    return {
      name: "some-cool-app-name",
      removal: input?.stage === "production" ? "retain" : "remove",
      home: "aws"
    };
  },
  async run() {
    const vpc = new sst.aws.Vpc("CAVPC", {
      nat: "ec2",
      bastion: true,
    });
    const rds = new sst.aws.Postgres("some-cool-app-db", { vpc });
    const cluster = new sst.aws.Cluster("CoolAppCluster", { vpc });
    const service = cluster.addService("CoolAppService", {
      scaling: {
        min: 1,
        max: 4,
        cpuUtilization: 50,
        memoryUtilization: 50,
      },
      serviceRegistry: {
        port: 3000,
      },
      containers: [
        {
          name: "admin",
          image: {
            context: "/admin-server",
            dockerfile: "/admin-server/dockerfile",
          },
        },
      ],
      link: [rds],
      loadBalancer: {
        // domain: "tbd-cool-app-domain.com",
        ports: [
          { listen: "80/http", forward: "3000/http" },
          // { listen: "443/https", forward: "3000/http" },
        ],
      },
    });
    const DATABASE_URL = $interpolate`postgresql://${rds.username}:${rds.password}@${rds.host}:${rds.port}/${rds.database}`;
    new sst.x.DevCommand("Prisma", {
      environment: { DATABASE_URL },
      dev: {
        autostart: false,
        command: "npx prisma studio",
      },
    });
  },
});
```

**Comment by jayair** [comment]
Yeah in dev we don't deploy your containers (and some other resources): https://sst.dev/docs/reference/cli#dev

For this reason we recommend not switching between the two.

<img width="673" alt="Screenshot 2024-11-22 at 6 41 32 PM" src="https://github.com/user-attachments/assets/072fb6c1-e090-48e3-b1dd-cddfdd803165">

Would recommend reading this: https://sst.dev/docs/workflow#dev

In an upcoming release we'll show a little warning when you do this. Closing for now.

**Comment by claridgicus** [comment]
@jayair 
I'm not sure I would have expected running a dev command to be able to delete something that was deployed to a personal stage - the warning is enough I guess.

**Comment by jayair** [comment]
Yeah it's not a good surprise.
