### ISSUE TITLE
console: failed to start runner

### ISSUE THREAD

**Issue by nguyendon** [anomalyco/sst#5106]
Getting this message when deploying. There are no other log messages.

<img width="455" alt="image" src="https://github.com/user-attachments/assets/95a90669-86ae-4789-9c2f-5f2bac07eaae">

**Comment by nguyendon** [comment]
I've tried to delete the CodeBuild projects as suggested on Discord but that hasn't helped.

**Comment by jayair** [comment]
We'll take a look.

**Comment by nguyendon** [comment]
Thanks @jayair . Another datapoint - I also tried to redeploy with a different compute instance type and that made no difference.

**Comment by fwang** [comment]
The issue was the CodeBuild project was removed from the AWS console.

Fixed. AutoDeploy will detect and auto-recreate the project.
