### ISSUE TITLE
StaticSite V3 - Add the ability to disable the CloudFront auto generated URL

### ISSUE THREAD

**Issue by keypuncherlabs** [anomalyco/sst#5111]
If the custom domain option is set to 'mydomain.com' than the autogenerated CloudFront URL should be disabled by default.

For SEO and potential other reasons, it would see like it should either be the default or at least provide another property to disable the CloudFront URL so that the hosted site does not have two separate URLs with identical content appearing to the search engines which can damage the ranking of the main domain.

I've done the same in Serverless Framework before migrating over to SST, so this would make a really great addition.

PROPOSED OPTION 1:
When I set a custom domain, then the CloudFront URL should not be accessible

PROPOSED OPTION 2:
When I set a custom domain, then there should be an attribute available to disable the autogenerated CloudFront URL

**Comment by jayair** [comment]
That's a good point. We'll take a look.

**Comment by fwang** [comment]
Releasing v3.3.33 with the feature - https://github.com/sst/sst/commit/a8be47cdaaf9532a255464bfd78cd6f0b4576287

If custom domain is set, the viewer request CloudFront function will return 403 for requests coming from the cloudfront domain.

**Comment by keypuncherlabs** [comment]
You guys rock! Thank you
