### ISSUE TITLE
Could not find an `sst dev` session 

### ISSUE THREAD

**Issue by Zboule** [anomalyco/sst#5115]
When running `npx sst dev - verbose` command is exiting immediatly with message
`Could not find an `sst dev` session to connect to. Since you are running a command outside of the multiplexer be sure to start `sst dev` first.`

Running the stack in basic mode `npx sst dev --mode=basic` is working fine.

SST version 3.3.27

**Comment by jayair** [comment]
Is this `npx sst dev --verbose`? Does it also happen with just `npx sst dev`?

**Comment by Zboule** [comment]
>Is this npx sst dev --verbose? Does it also happen with just npx sst dev?
With just `npx sst dev` it was just exiting right away without any message / error

Some of the typescript import where pointing to wrong path. Fixing them resolved the problem.
Closing this issue but it may require some follow up to ensure typescript errors are properly exposed to the user.
