### ISSUE TITLE
Docs: `feature: sst.aws.Bus` issue lost after move from sst/ion

### ISSUE THREAD

**Issue by syhner** [anomalyco/sst#5129]
Old issue (https://github.com/sst/ion/issues/67) is referenced in the current v2 migration guide

https://github.com/sst/sst/blob/9e31b7081d84c37be550d3e7389867aef27efcad/www/src/content/docs/docs/migrate-from-v2.mdx?plain=1#L37

but leads to a 404 since the move from sst/ion to sst/sst

**Comment by jayair** [comment]
Thanks just fixed all the links in that section.
