### ISSUE TITLE
QOL: remove trailing slashes from resource url (`sst.aws.Function`)

### ISSUE THREAD

**Issue by syhner** [anomalyco/sst#5149]
a consideration for the core team

currently `sst.aws.Function` urls have trailing slashes e.g. `https://example.lambda-url.eu-central-1.on.aws/`

would be nice to be able to make requests to `${Resource.Backend.url}/route` without having to trim the trailing slash first

posted about this some time ago but it didn't get much traction (at least publicly) — happy for this to be closed if not desired

<img width="757" alt="image" src="https://github.com/user-attachments/assets/916156ab-655b-445a-bc8b-34d5c26a81ea">

**Comment by jayair** [comment]
Yeah that's a good point. I wonder if they changed recently. Let me tell the team.

**Comment by fwang** [comment]
@syhner thanks for the explanation!

I think the trailing slash should be kept b/c:
- the canonical format for a root domain url should has the trailing slash
- consistent w/ what Lambda returns
- this would be a breaking change

If more ppl complain about this, perhaps SST also expose `Resource.Backend.cleanUrl`? I don't know if i like it lol.

Let's close this for now.
