### ISSUE TITLE
Console: Create Workspace/Looking up apps doesn't work

### ISSUE THREAD

**Issue by KaviiSuri** [anomalyco/sst#5150]
I tried doing this with an old account and a brand new account. I cannot create a new workspace in the console, and the apps list is stuck on loading for me. 

Here's a demo of this happening: https://www.loom.com/share/718075560d084ba99865d6b58264da35?sid=7049cb12-b395-4239-b8c5-339450881e53

**Comment by jayair** [comment]
Thanks for the video. Just pushed a fix. Give it a try and let me know?

**Comment by KaviiSuri** [comment]
Verified! Works now! Thanks for the quick help!
