### ISSUE TITLE
Failure creating NAT instance

### ISSUE THREAD

**Issue by HishamAli81** [anomalyco/sst#5151]
When attempting to create a VPC with an EC2 NAT:

```
new sst.aws.Vpc('vpc', { az: 2, bastion: true, nat: 'ec2' });
```

The following error is thrown when deploying to the ap-southeast-5 AWS region:

```
✕  Failed    
   Error: invocation of aws:ec2/getAmi:getAmi returned an error: invoking aws:ec2/getAmi:getAmi: 1 error occurred:
       * Your query returned no results. Please change your search criteria and try again.
   
   
       at Object.callback (/home/runner/work/.sst/platform/node_modules/@pulumi/aws/node_modules/@pulumi/runtime/invoke.ts:285:37)
       at Object.onReceiveStatus (/home/runner/work/.sst/platform/node_modules/@grpc/grpc-js/src/client.ts:360:26)
       at Object.onReceiveStatus (/home/runner/work/.sst/platform/node_modules/@grpc/grpc-js/src/client-interceptors.ts:458:34)
       at Object.onReceiveStatus (/home/runner/work/.sst/platform/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48)
       at /home/runner/work/.sst/platform/node_modules/@grpc/grpc-js/src/resolving-call.ts:132:24
       at processTicksAndRejections (node:internal/process/task_queues:77:11) {
     promise: Promise { <rejected> [Circular *1] }
   }
```

After some investigation, the reason for the failure is that the ap-southeast-5 AWS region doesn't have the fck-nat public AMIs pre-installed.

I then manually copied the AMIs from the us-east-1 region into ap-southeast-5. And for some additional context, I was unable to perform a straight copy of the fck-nat image and had to create a new image because of this issue: https://github.com/AndrewGuenther/fck-nat/issues/82

However, I'm currently blocked because the vpc.createNatInstance() function hardcodes the owner id to [568608671756](https://github.com/sst/sst/blob/7025b3301f6091e2e33358436d502d6cbb713902/platform/src/components/aws/vpc.ts#L859):

```
const ami = ec2.getAmiOutput(
  {
    owners: ["568608671756"], // AWS account ID for fck-nat AMI
    filters: [
      {
        name: "name",
        // The AMI has the SSM agent pre-installed
        values: ["fck-nat-al2023-*"],
      },
      {
        name: "architecture",
        values: ["arm64"],
      },
    ],
    mostRecent: true,
  },
  { parent },
);
```

In this case, since I re-created the image, my account is the owner of the image. Would it be possible to either:

1. Remove the owner restriction
2. Add the current account into the owners array by default
3. Allow for the owners array to be configurable
4. Allow for the AMI id to be configurable, and skip the fck-nat AMI search if the id is specified.

**Comment by jayair** [comment]
Hmm interesting. Let me ask the team.

**Comment by HishamAli81** [comment]
And FYI, I have also tried performing a transform to override the AMI id:

```
export const vpc = new sst.aws.Vpc('vpc', {
  az: 2,
  bastion: true,
  nat: 'ec2',
  transform: {
    natInstance: {
      ami: 'ami-MY_AMI_ID',
    },
  },
});
```

However, it still fails with the same error because the fck-nat AMI search is being performed before the transform.

**Comment by fwang** [comment]
Added support in v3.3.38.

```ts
{
  nat: {
    ec2: {
      ami: "ami-1234567890abcdef0"
    }
  }
}
```

**Comment by HishamAli81** [comment]
@fwang @jayair Thanks for the quick turnaround, appreciate it!

**Comment by AndrewGuenther** [comment]
I didn't realize SST was using fck-nat, that's awesome! I've opened an issue to get fck-nat 1.3 copied to ap-southeast-5: https://github.com/AndrewGuenther/fck-nat/issues/105

**Comment by fwang** [comment]
Awesome! Thanks @AndrewGuenther
