### ISSUE TITLE
Support PostgreSQL role and user creation

### ISSUE THREAD

**Issue by vimtor** [anomalyco/sst#5161]
I was trying to create a custom read-only role in my primary PostgreSQL instance so my Metabase could connect to it. For context, I was following this guide: https://www.metabase.com/docs/latest/databases/users-roles-privileges

I created the role through SQL as the guide explains, but when I tried to connect from Metabase, I got this error:

```
This RDS proxy has no credentials for the role metabase. Check the credentials for this role and try again.
```

After some research I found that for creating users when using RDS you should create them via secrets manager. Currently the `proxy` resource is not being exposed throught `transform` (#5162). However I thought that it would make even more sense for SST to have an API like this:

```ts
const postgres = new sst.aws.Postgres("Postgres", { vpc });

const password = new sst.Secret("MetabasePassword");

const user = postgres.addUser("MetabaseUser", {
  name: "metabase",
  login: true,
  password: password.value,
  privileges: ["SELECT"],
});
```

**Comment by fwang** [comment]
In v3.3.65, u can pass in additional proxy credentials:
```ts
proxy: {
  credentials: [
    { username: "frank", password: "welcome"}
  ]
}
```

Note, this doesn't create the users in the database. You'd need to do that manually.

**Comment by vimtor** [comment]
> Note, this doesn't create the users in the database. You'd need to do that manually.

How would you create the users in the database so they can use those credentials then?
