### ISSUE TITLE
Deployment Failure - could not read plugin resource-aws-v6.62.0/pulumi-resource-aws

### ISSUE THREAD

**Issue by backnotprop** [anomalyco/sst#5163]
**Describe the bug:**  
When deploying with SST on Mac ARM using Node.js 22.11, the deployment fails with the following error: 

```
panic: fatal: error An assertion has failed: Failed to read schema-embed.json. source error: read schema-embed.json/: is a directory
goroutine 1 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
...
|  could not read plugin [/Users/ramos/Library/Application Support/sst/plugins/resource-aws-v6.62.0/pulumi-resource-aws] stdout: EOF
```

**Steps to reproduce:**
1. Use Mac ARM architecture.
2. Node.js version: 22.11.
3. Deploy with SST using `npx sst deploy --stage production`.
(using latest version of sst, plus a couple tries with downgraded to 3.3.x)

**Expected behavior:**  
Deployment should complete without errors.

**Actual behavior:**  
Deployment fails with the assertion error, indicating `schema-embed.json` is treated as a directory.

**Environment:**
- OS: macOS (ARM architecture)
- Node.js version: 22.11
- SST version: 3.3.40
- Pulumi plugin: AWS v6.62.0

**Additional context:**  
This seems to affect the latest versions of SST and Pulumi. Reinstalling plugins and clearing caches did not resolve the issue.

-- 

Assuming it's either an issue with pulumi and SST using their latest creating regression? or something about my setup.

**Comment by turingAlan** [comment]
Yes, it appears that this issue emerged around 7-8 hours ago. We are using SST for our NextJS application, and this issue has completely broken our deployment any suggestions/help what could be done

**Comment by samswitz** [comment]
Just got the same issue today when trying to deploy a simple Next.js application, it worked yesterday.

**Comment by the-simian** [comment]
@turingAlan , @samswitz 
you have to pin the aws version:

 this is in your `sst.config.ts` file
```js
      providers: {
        aws: {
          version: '6.61.0', //<------
          region: AWS_REGION,
        },
      },
 ```     
 
 I also pinned my pulumi dep: `"@pulumi/aws": "6.61.0",` in package.json
 
 somethings wrong in the 6.62.x version
 
 I was getting this exact issue. I added the `version` property in the args and now it passes.

**Comment by turingAlan** [comment]
Got it thanks @the-simian

**Comment by arjunyel** [comment]
Should be fixed upstream now https://github.com/pulumi/pulumi-aws/pull/4867

**Comment by jayair** [comment]
We should automatically pull the latest version of the provider. Can you confirm? Or if we need to do something on our end?

**Comment by arjunyel** [comment]
@jayair it's fixed now, you can close
