### ISSUE TITLE
Resource comment gets too long via join

### ISSUE THREAD

**Issue by lew** [anomalyco/sst#5168]
The following code https://github.com/sst/sst/blob/4f264e84e48f131bed9739dd00677fa216c6ac46/platform/src/components/aws/https-redirect.ts#L80 is causing an error for several/long redirect domains:  
```Distribution resource 'xyz' has a problem: expected length of comment to be in the range (0 - 128)```

Expected Behavior:
The comment should remain within the 128-character limit, ensuring successful deployment.

Proposed Solution:
Truncate the comment to fit within the limit (e.g., showing a preview of domain names with ellipses)

**Comment by jayair** [comment]
Good call
