### ISSUE TITLE
Ability to specify Security Groups for EFS

### ISSUE THREAD

**Issue by cmanou** [anomalyco/sst#5170]
It would be great to be able to be able to provide security groups to an efs mount, useful for when you launch services with particular security groups currently they end up in the default sg for the vpc. Currently there is no direct arg or transform for mount targets which is what the sg is passed to.

**Comment by fwang** [comment]
Releasing v3.3.66.

EFS no longer uses the default SG. It now creates its own SG with the same ingress/egress as the default SG, and u can transform it.
