### ISSUE TITLE
Lambda function invoked many times.

### ISSUE THREAD

**Issue by rupertlssmith** [anomalyco/sst#5172]
This started happening recently, when I was making some code changes so I though it must be my fault. I rolled back those edits and restarted `npx sst dev` but and even on the first invokation this happens.

When you invoke 1 lambda function once during dev, it appears to be invoked many time by the hot-relead runner. See attached screen shot.
![multi-invoke](https://github.com/user-attachments/assets/6c8c3ccd-6b61-422d-b8f7-9db48e663723)

Not sure what is going on, or even if it is a problem! Since one of the invokations seems to run and provide the expected response. Just looks weird that this happens and happens for no apparent reason.

**Comment by rupertlssmith** [comment]
https://github.com/sst/sst/issues/5173

Around the same time I got the above I had this "https://github.com/sst/sst/issues/5173" message. 

After that it started running normally with one message per invokation. Seems like there were some dangling threads somehow? Possibly in the Lambda runner on the AWS side, since I had killed `sst dev` in between invokations and was still seeing the message. I would guess some unhandled exception left things into limbo in the Lambda dev runner.

**Comment by jayair** [comment]
I'll close this issue then. Let's look at the other one.

**Comment by rupertlssmith** [comment]
I cannot re-open or I would. 

This happens a lot, I would say on most `sst dev` session. It will start with 1 Invoke per call, and then gradually increase over time to 2, 3, ... Usually I will have killed `sst dev` and started another session about then, but if you keep going, the Invokes per actual call only increases.

**Comment by rupertlssmith** [comment]
I will upgrade to latest and re-try it. If its still a problem, I will open a new issue for it.
