### ISSUE TITLE
Minor: Postgres - parameter group args use `postgres16`

### ISSUE THREAD

**Issue by isaacharrisholt** [anomalyco/sst#5175]
I can't create a Postgres DB using `sst.aws.Postgres` with Postgres 17 without needing to `transform` the parameter group. It would be great if SST could figure out the correct version based on the version of Postgres requested.

Required workaround:

```ts
new sst.aws.Postgres("...", {
	vpc,
	version: "17.2",
	transform: {
		parameterGroup: (parameterGroupArgs) => {
			parameterGroupArgs.family = "postgres17";
		},
	},
});
```

To replicate, just run this, removing the transform.

**Comment by fwang** [comment]
Released in v3.3.68.
