### ISSUE TITLE
add mfa constraints to docs for cognito user pool

### ISSUE THREAD

**Issue by ekaya97** [anomalyco/sst#5177]
**Refers to Docs**
https://sst.dev/docs/component/aws/cognito-user-pool#mfa

**Requested Change**
Please add that when MFA is "optional" or "on", at least one of sms_configuration or software_token_mfa_configuration is required.

**Resources**
https://www.pulumi.com/registry/packages/aws/api-docs/cognito/userpool/#mfaconfiguration_nodejs

**Reason for change**
Spent way too long trying to figure out why I was getting an error...
"Invalid MFA configuration given, can't disable all MFAs with a required or optional configuration."

**Comment by jayair** [comment]
Good callout. Thanks. I'll add it.
