### ISSUE TITLE
Importing sst.Resource in my nestjs project is causing an ESM error

### ISSUE THREAD

**Issue by claridgicus** [anomalyco/sst#5193]
Hello friends

I'm bumping into an issue developing my nestjs application inside my SST monorepo
It's nothing special but I want to pull in the env vars correctly

### What I've done:

Versions/Stuff
SST v3 - latest
NodeJs v20.11.1
Monorepo setup with a package that contains a brand spanking new Nestjs install
running npm run start:dev
 
```
import { Resource } from 'sst'; 

@Controller()
export class AuthController {
  constructor(private authService: AuthService) {}

  @Get('example') 
  async example(@Req() req, @Res() res) { 
      res.redirect(`${Resource.AdminUi.url}/oauth?token=${token.jwt}`);
  }
}
```

### What happens
Building the app throws something like this

```
/home/projectpath/packages/admin-server/dist/auth/controllers/auth.controller.js:17
const sst_1 = require("sst");
              ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/projectpath/node_modules/sst/dist/index.js from /home/projectpath/packages/admin-server/dist/auth/controllers/auth.controller.js not supported.
Instead change the require of index.js in /home/projectpath/packages/admin-server/dist/auth/controllers/auth.controller.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/projectpath/packages/admin-server/dist/auth/controllers/auth.controller.js:17:15) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.11.1
```

### Expected behaviour

I think I probably should just be able to load it without having to tinker with a tsconfig or dynamic import anything

### Workaround:

Dynamic importing seems to work 

`let Resource = (await import('sst')).Resource;`

``` 
@Controller()
export class AuthController {
  constructor(private authService: AuthService) {}

  @Get('example') 
  async example(@Req() req, @Res() res) { 
      let Resource = (await import('sst')).Resource;
      res.redirect(`${Resource.AdminUi.url}/oauth?token=${token.jwt}`);
  }
}
```

But it's a bit messy and not intuitive based on the errors thrown, probably merits a look in or a bit of documentation.

**Comment by claridgicus** [comment]
Going to node 22 and using --experimental-require-module resolved the issue - but I'd say its something to document again. Happy to submit a pr for docs if you can point me where you'd like them entered.

**Comment by jayair** [comment]
Oh this is good. I couldn't get this to work before. I'm guessing this new flag makes it possible?

**Comment by claridgicus** [comment]
@jayair I'm willing to bash my head into a problem for you any time.

But yes it's doing the trick for me.

an .npmrc file in the root of the project

with the contents of
node-options=--experimental-require-module

allows me to not tamper with too much to get it working.

**Comment by jayair** [comment]
Interesting, yeah let me add it to my list to test out and add an example.

**Comment by NickReisenauer** [comment]
Getting this too in a express+docker+sst setup, but using the very latest sst-ion.
Node: v18.20.4
SST: v3.4.32

`Error [ERR_REQUIRE_ESM]: require() of ES Module /node_modules/sst/dist/index.js from /dist/src/sequelize/index.js not supported.
`

**Comment by jayair** [comment]
@NickReisenauer yeah Nest doesn't support ESM so you'll need a newer Node and that flag @claridgicus has.

**Comment by NickReisenauer** [comment]
@jayair I realize this is a Nest tagged issue but right now we're just on Express + Node. I tried `require('sst')` and that didn't work either so I'll give updating Node a try with that flag and see how it goes for us. Thanks!

**Comment by jayair** [comment]
Ah yeah you'll need to do an `import`.

**Comment by jayair** [comment]
Used it to add a quick start https://sst.dev/docs/start/aws/nestjs

Thanks @claridgicus
