### ISSUE TITLE
Pages Router APIs not working after migration to SST v3

### ISSUE THREAD

**Issue by gabriel-wow** [anomalyco/sst#5203]
My company has a large project built with **Next.js 12**. As Next.js 12 is now outdated, we updated our project to **Next.js 14** while **keeping the Pages Router structure**. Previously, we were using **cdk-nextjs-standalone** to deploy the application to **AWS**, and everything was working fine.
However, **after upgrading to Next.js 14 and deploying**, our **API routes topped functioning**. To resolve this, we decided to migrate to the **SST framework (v3)**. Despite completing the migration and configuration, our **API routes are still not working** and continue sending us to 404 page.
```
Versions:
Next.js: v14.2.20
SST: v3.3.65
OpenNext.js: 3.2.2
```
**Steps Taken:**

- Updated **Next.js from v12 to v14** (keeping the Pages Router structure).
- Migrated deployment from cdk-nextjs-standalone to SST (v3).
- Configured the SST project following the documentation.

**Even after successfully deploying the project with SST v3, our API routes are unresponsive.**

**Comment by jayair** [comment]
It might be better to ask this over on the OpenNext side https://github.com/opennextjs/opennextjs-aws

**Comment by fthomasvp-wow** [comment]
Hi @jayair ,

Thanks for replying!

The OpenNext team confirmed this issue and provided us with a workaround.
https://github.com/opennextjs/opennextjs-aws/issues/677

**Comment by jayair** [comment]
Sounds good. I'll close this for now.
