### ISSUE TITLE
Run Playwright with SST

### ISSUE THREAD

**Issue by radokristof** [anomalyco/sst#5205]
Is it possible to run tests created with Playwright to run it in an SST environment?

I have seen example for `vitest` for `v2`, but I'm using v3 and and I would prefer e2e tests.

Thank you!

**Comment by arpadgabor** [comment]
You should be able to run `pnpm sst shell -- <your playwright command>` and it will inject links for you.

You can also use this too `pnpm sst shell -- printenv` to see what env vars SST generates.

**Comment by radokristof** [comment]
Thank you @arpadgabor!
Looks like the sst dev (live) server is not launched when running sst shell

**Comment by radokristof** [comment]
I was able to get it working by running `sst dev` separately and the running `npx sst shell -- playwright test`

However, did anyone tried running a similar setup in CI/CD? Github Actions is not really designed to run parallel commands.

**Comment by paolostyle** [comment]
You should probably just run Playwright on a deployed environment in CI tbh

**Comment by radokristof** [comment]
Makes sense, thank you!
