### ISSUE TITLE
`sst deploy` closes with non-error exit code even if there was an error

### ISSUE THREAD

**Issue by vimtor** [anomalyco/sst#5211]
I got this error in my GitHub Actions #5210, but it took a while to track down because the GitHub Action was completing without showing any errors. I'm on the latest SST version `3.4.3`.

![CleanShot 2024-12-14 at 14 27 18@2x](https://github.com/user-attachments/assets/0134bef4-72f1-41d5-b361-8a73ad7ec618)

Notice that it completed successfully even though it encountered an error.

**Comment by jayair** [comment]
That's odd @thdxr

**Comment by klaemo** [comment]
Just noticed this as well
<img width="847" alt="image" src="https://github.com/user-attachments/assets/fc6268e0-4fc6-42ab-865e-b559662b25a8" />

**Comment by arjunyel** [comment]
@klaemo unrelated to this issue but your specific issue should be fixed with version 3.4.7

**Comment by thdxr** [comment]
should be fixed in 3.4.17
