### ISSUE TITLE
Excessive sst Processes Causing MacBook Overheating

### ISSUE THREAD

**Issue by dror-weiss** [anomalyco/sst#5217]
I've noticed my MacBook overheating and identified the cause as a large number of sst processes running. This seems to be related to issues with dev deployments hanging. To resolve this, I had to repeatedly go through a cycle of killing processes, unlocking resources, and restarting development.

There is a hidden bug somewhere.

```bash
❯ sst version
sst 3.4.5
```

<img width="1011" alt="image" src="https://github.com/user-attachments/assets/5269817a-321d-4b53-bc8f-3a6744a7f7af" />

**Comment by arjunyel** [comment]
Try 3.4.21

**Comment by dror-weiss** [comment]
Looks better. If I see this behavior again I'll open another issue.

**Comment by jmcmacnz** [comment]
I'm getting the same thing, on 3.13.11 and no terminal open 

![Image](https://github.com/user-attachments/assets/b1995349-8da3-47e4-8c57-4868328c1905)

**Comment by jayair** [comment]
@jmcmacnz open a new issue? Also share some of the logs from your sst log?
