### ISSUE TITLE
[Bug] Docker build crash (sst linkables)

### ISSUE THREAD

**Issue by agamm** [anomalyco/sst#5227]
When trying to deploy a Cluster (docker) with nextjs that is using Linkables, my docker build crashes with:
```
#25 193.0  ✓ Compiled successfully
#25 193.1    Linting and checking validity of types ...
#25 215.8    Collecting page data ...
#25 218.0 Error: It does not look like SST links are active. If this is in local development and you are not starting this process through the multiplexer, wrap your command with `sst dev -- <command>`
```

Folder structure:
```
./app
./types
Dockerfile
sst.config.ts
```

pnpm-workspace.yaml:
```
packages:
- "app"
- "types"
```

Sst config:
```
const vpc = new sst.aws.Vpc("MyVpc", { bastion: true });
const cluster = new sst.aws.Cluster("MyCluster", { vpc });

cluster.addService("MyNextService", {
	link: [
		openaiSecret, 
	],
	image: {
		dockerfile: "./Dockerfile",
	},
	loadBalancer: {
		domain: {
			name: organization.domain,
			dns: sst.cloudflare.dns(),
		},
		ports: [{ listen: "80/http", forward: "3000/http" }],
	},
	dev: {
		command: "pnpm --filter=app dev",
	},
});
```

Dockerfile:
```
# syntax=docker.io/docker/dockerfile:1

FROM node:lts-alpine AS base

# Install dependencies only when needed
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json pnpm-lock.yaml .npmrc* ./
RUN corepack enable pnpm && pnpm i --frozen-lockfile

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY ./app ./app
COPY ./types ./types
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY sst-env.d.ts* ./
RUN corepack enable pnpm && pnpm i --filter types
RUN corepack enable pnpm && pnpm i --filter app

# Uncomment the following line in case you want to disable telemetry during the build.
ENV NEXT_TELEMETRY_DISABLED=1

RUN corepack enable pnpm && pnpm run build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
# Uncomment the following line in case you want to disable telemetry during runtime.
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# Automatically leverage output traces to reduce image size
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000

# server.js is created by next build from the standalone output
ENV HOSTNAME="0.0.0.0"
CMD ["node", "server.js"]
```

Related: https://github.com/sst/sst/issues/5206

**Comment by agamm** [comment]
I also tried to add `ARG SST_RESOURCE_OpenAIKey` for all the relevant secrets but I get the same error.

**Comment by jayair** [comment]
Hmm I don't recall getting this the last time I tried. Is it possible to try it in a non-monorepo setting just to check?

**Comment by agamm** [comment]
> Hmm I don't recall getting this the last time I tried. Is it possible to try it in a non-monorepo setting just to check?

@jayair Yeah today I created a new sst setup and it still fails, I think this is a crash because of sst resources + the next build phase - I think next build in the docker process doesn't have access to the sst `Resource`.

> Error: It does not look like SST links are active.

Here is the test repo I hope it helps:
https://github.com/agamm/sst-next-docker-bug (the README.md explains it)

This is really frustrating; I would love to just use [aws.Nextjs with a docker attribute](https://github.com/sst/sst/issues/5206) :)

**Comment by jayair** [comment]
Let me play around with it.

The Nextjs component using something other than Lambda is a bit trickier because it's tied to OpenNext's implementation.

**Comment by agamm** [comment]
@jayair  It only happens if I use an SST resource in a next.js static page, when I do `export const dynamic = "force-dynamic";` it works. The problem is that using in my `layout.tsx` so it is statically generated.

PS As for the Next.js component, it would be nice if it would even abstract the cluster for me without the OpenNext implementation :)

**Comment by jayair** [comment]
Yeah I tried it out. SST runs docker build with the environment variables for the links but if you need the Next.js build to have access to it, it needs to be declared in the Dockerfile. It needs to be done for each resource, in your case you were using the `App` so I added this above the build command.

```
ARG SST_RESOURCE_App 

RUN npm run build
```

Not sure why your secrets didn't work from before, but feel free to reopen if you have a repo to reproduce that.

I added a note about this in the Next.js container tutorial.
