### ISSUE TITLE
Add a WAF construct for protecting API endpoints

### ISSUE THREAD

**Issue by fwang** [anomalyco/sst#949]
Ross suggested:
> WAF integration with sensible defaults would be a very cool SST feature. The config of that thing is complex

Requests:
- https://serverless-stack.slack.com/archives/C01HYQRUGG6/p1634812549001700
- https://serverless-stack.slack.com/archives/C01JG3B20RY/p1634837656033300

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
